networks:
  cloudflared-net:
    external: true
  pizzaai-net:
    driver: bridge

services:
  pizzaai-backend:
    container_name: pizzaai-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - cloudflared-net
      - pizzaai-net
    volumes:
      - pizzaai_dataprotection:/app/data-protection-keys
    secrets:
      - source: cert_password
        target: CERT_PASSWORD
      - source: openai_key
        target: OPENAI_KEY
    environment:
      - CERT_PATH=/app/certs
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ALLOWEDHOSTS=api-pizzaai.jesuisdavid.dev
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
      - CORS_ORIGINS=https://pizzaai.jesuisdavid.dev
      - PORT=8080
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3
    user: 'app:app'

  pizzaai-frontend:
    container_name: pizzaai-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - cloudflared-net
      - pizzaai-net
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: ng serve --host 0.0.0.0 --port 4200 --configuration=production
    environment:
      - NODE_ENV=production

volumes:
  node_modules:
  pizzaai_dataprotection:

secrets:
  cert_password:
    file: ./secrets/cert_password.txt
  openai_key:
    file: ./secrets/openai_key.txt
