networks:
  cloudflared-net:
    external: true

services:
  pizzaai:
    container_name: pizzaai
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CSP_NONCE: ${CSP_NONCE}
    networks:
      - cloudflared-net
    volumes:
      - pizzaai_dataprotection:/app/data-protection-keys
    secrets:
      - source: csp_nonce
        target: CSP_NONCE
      - source: cert_password
        target: CERT_PASSWORD
      - source: openai_key
        target: OPENAI_KEY
    environment:
      - NODE_ENV=production
      - CERT_PATH=/app/certs
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ALLOWEDHOSTS=pizzaai.jesuisdavid.dev
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
      - CORS_ORIGINS=https://pizzaai.jesuisdavid.dev
      - PORT=8080
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3
    user: 'app:app'

volumes:
  pizzaai_dataprotection:

secrets:
  csp_nonce:
    file: ./secrets/nonce.txt
  cert_password:
    file: ./secrets/cert_password.txt
  openai_key:
    file: ./secrets/openai_key.txt
